campaigns:
  host: <%= ENV.fetch('CAMPAIGNS_HOST') { 'tugo_campaigns_app_1:50051' } %>

common:
  host: <%= ENV.fetch('COMMON_HOST') { 'tugo_common_app_1:50051' } %>

contacts:
  host: <%= ENV.fetch('CONTACTS_HOST') { 'tugo_contacts_app_1:50051' } %>

leads:
  host: <%= ENV.fetch('LEADS_HOST') { 'tugo_leads_app_1:50051' } %>

organizations:
  host: <%= ENV.fetch('ORGANIZATIONS_HOST') { 'tugo_organizations_app_1:50051' } %>

env:
  name: <%= ENV['ENV_NAME'] %>

encrypted_password:
  pepper: '0c926a9f54004241775fbec5df837607f04a06f096c76a24efe37a70992cbfbf'
  stretches: 12